### ISSUE TITLE
Error while updating anaconda: pre-unlink script failed for package conda-forge::jupyterlab-0.31.5-py36_1 

### ISSUE THREAD

**Issue by taserian** [conda-forge/jupyterlab-feedstock#104]
WARNING conda.core.link:run_script(518): pre-unlink script failed for package conda-forge::jupyterlab-0.31.5-py36_1 
consider notifying the package maintainer

**Comment by blink1073** [comment]
This warning can be ignored: it means that we tried to uninstall the jupyterlab server extension but jupyter itself was already uninstalled.
