### ISSUE TITLE
Transitioning to the conf.d enabling approach

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/jupyterlab-feedstock#111]
We currently explicitly enable/disable the server extension in the link/unlink scripts. We should eventually transition to only using the conf.d approach (which already works), when we feel that enough time has passed that most people have upgraded to the relevant notebook version (I think 5.3, released in January 2018).

A transition plan is outlined in https://github.com/jupyter/notebook/issues/3782 - which is complicated by the fact that we can't just do `jupyter serverextension uninstall` to remove the config entry. Basically, the transition plan involves removing the unlink scripts for several JupyterLab versions, so that most people have a jlab conda package that won't explicitly disable jlab on uninstall. Then remove the link scripts. The end result is that people will have a harmless `enable` entry in their notebook server config after upgrading, but installs into new environments will use the conf.d enabling only.

**Comment by blink1073** [comment]
👍

**Comment by jasongrout** [comment]
I propose that we start the transition by deleting the unlink scripts with the next version of JupyterLab, and wait at least 6 months (i.e., a year after notebook 5.3 was released) for people to move to these newer versions of JupyterLab before deleting the link scripts.

**Comment by blink1073** [comment]
Sounds good to me

**Comment by jasongrout** [comment]
> I propose that we start the transition by deleting the unlink scripts with the next version of JupyterLab, and wait at least 6 months (i.e., a year after notebook 5.3 was released) for people to move to these newer versions of JupyterLab and the notebook before deleting the link scripts.

Let's try to remember to delete the unlink scripts for the 0.35 release.

**Comment by jasongrout** [comment]
I deleted the unlink scripts in #144 (jlab 0.35). I think we probably can delete the link scripts and move to noarch in the next version, which will probably be maybe 10 months after notebook 5.3 was released?

**Comment by blink1073** [comment]
Sounds good, thanks!

**Comment by jasongrout** [comment]
Oops, we should have done this for 1.0. I suppose we can do it for 1.1, though. I hesitate to make this change in a patch release, though.

**Comment by jasongrout** [comment]
I'm doing a trial run of switching to the noarch package in the new prerelease branch.
