### ISSUE TITLE
Pin tornado to <6

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/jupyterlab-feedstock#156]
This is just a reminder that the python package is pinned to `tornado<6`, so we'll need to pin here as well.

**Comment by ian-r-rose** [comment]
@jasongrout This should be safe to close now, correct?

**Comment by jasongrout** [comment]
Yes, thanks!

**Comment by jakirkham** [comment]
Yep, handled in PR ( https://github.com/conda-forge/jupyterlab-feedstock/pull/158 ). Though I think how Tornado gets pinned was changed along the way.
