### ISSUE TITLE
Remove LICENSE from this repo?

### ISSUE THREAD

**Issue by ian-r-rose** [conda-forge/jupyterlab-feedstock#160]
According to the conda-forge docs, the `LICENSE` file should only be in the feedstock if it is not distributed with the package. Since JupyterLab does distribute its license, can we remove it here?

https://conda-forge.org/docs/maintainer/adding_pkgs.html#about

**Comment by ian-r-rose** [comment]
nvm, wrong file

**Comment by jakirkham** [comment]
Ah yeah that's meaning a license file in the recipe. Maybe we could clarify the docs if that is confusing. Would you be willing to open an issue on [the webpage repo]( https://github.com/conda-forge/conda-forge.github.io )?

**Comment by ian-r-rose** [comment]
Sure, I can open an issue, though I'm also perfectly happy to chalk this up to me being a space-cadet :)

**Comment by jakirkham** [comment]
If you got confused, I think it's more likely someone who knows way less about conda-forge or conda packaging will also be confused. So I'd argue you helped us find a doc bug. 😉
