### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/jupyterlab-feedstock#161]
Right now, this command fails on windows:

```
> conda create -n jlabtutorial -c conda-forge --override-channels jupyterlab=1
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - jupyterlab=1 -> jupyterlab_server[version='>=1.0.0,<2.0.0'] -> jsonschema[version='>=3.0.1'] -> pyrsistent[version='>=0.14.0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> vc=14
  - jupyterlab=1 -> jupyterlab_server[version='>=1.0.0,<2.0.0'] -> jsonschema[version='>=3.0.1'] -> functools32

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
It seems that jsonschema is maybe the problem?

CC @ian-r-rose, @jakirkham

**Comment by jasongrout** [comment]
In fact this also has a problem:

```
>conda create -n jlabtutorial -c conda-forge  python=3.7 nodejs
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nodejs -> vs2015_runtime
  - python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> vc=14

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mwcraig** [comment]
@mariusvniekerk -- any ideas here?

**Comment by ian-r-rose** [comment]
@jasongrout Perhaps related to https://github.com/conda-forge/jupyterlab_server-feedstock/pull/9 , from 5 days ago?

**Comment by mwcraig** [comment]
@jasongrout -- as a workaround, don't use the --override-channels option. pulling from defaults and conda-forge seems to work (the environment is currently installing, so I haven't tested functionality yet)

**Comment by mwcraig** [comment]
It looks like the issue is that neither `vc` nor `vs_2015_runtime` are in conda-forge on the main label.

**Comment by mwcraig** [comment]
@jasongrout -- the decision was mad to stop vendoring the microsoft runtimes in conda-forge because 1) doing so was causing conflicts within conda-forge because of compilation against different versions of the runtime and 2) conda-forge does not build the runtime. The runtimes are pulled from defaults.

You can accomplish what you want (conda-forge first, ignoring whatever other channel settings the user may have) with:

```
conda create -n jlabtutorial --strict-channel-priority -c conda-forge -c defaults  --override-channels python=3.7 nodejs
```

When I do that on windows everything comes from conda-forge except the runtimes, which are pulled from defaults.

I don't think there is anything to fix -- if this workaround works for you the issue can be closed.

**Comment by jasongrout** [comment]
> the decision was mad to stop vendoring the microsoft runtimes

I assume you mean "made", not "mad" as in it was insane to stop vendoring runtimes?

**Comment by mwcraig** [comment]
Oops, yes "made" 🤣

**Comment by mariusvniekerk** [comment]
@mwcraig Thats the correct approach.

**Comment by jasongrout** [comment]
To be more precise, for people that have redefined the defaults channel, this works:

```
conda create -n jlabtutorial --strict-channel-priority -c conda-forge -c anaconda  --override-channels python=3.7 nodejs
```
Does that look right to you?

**Comment by jasongrout** [comment]
Also this works:
```
conda create -n jlabtutorial --strict-channel-priority -c conda-forge -c anaconda  --override-channels jupyterlab=1
```
I suppose if you wanted to be really strict, you'd do something like
```
conda create -n jlabtutorial --override-channels -c anaconda <vc runtime packages>
conda activate jlabtutorial
conda install --override-channels -c conda-forge <rest of packages>
```

Thanks again! Closing as answered
