### ISSUE TITLE
Can't install conda-forge jupyterlab and python >=3.7 on win-64

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyterlab-feedstock#209]
This is very possibly not an issue with this feedstock... but I am prevented from installing _any_ `jupyterlab` in a windows env with `python>=3.7.0`.

Running on a lab `master` binder:

```bash
conda info
```

```bash
     active environment : notebook
    active env location : /srv/conda/envs/notebook
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /srv/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-91-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:0
             netrc file : None
           offline mode : False

```

```bash
CONDA_SUBDIR=win-64 conda create --dry-run -n foo -c conda-forge jupyterlab 'python>=3.7'
```
```bash
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
jupyterlab -> jinja2[version='>=2.10'] -> python[version='>=3.8,<3.9.0a0']
jupyterlab -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|3.4.*']
python[version='>=3.7']
```

3.6 is fine:
<details>
<pre>
CONDA_SUBDIR=win-64 conda create --dry-run -n foo -c conda-forge jupyterlab 'python>=3.6'
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda

## Package Plan ##

  environment location: /srv/conda/envs/foo

  added / updated specs:
    - jupyterlab
    - python[version='>=3.6']

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-19.3.0               |             py_0          35 KB  conda-forge
    backcall-0.1.0             |             py_0          13 KB  conda-forge
    bleach-3.1.4               |     pyh9f0ad1d_0         111 KB  conda-forge
    ca-certificates-2020.4.5.1 |       hecc5488_0         184 KB  conda-forge
    certifi-2020.4.5.1         |   py36h9f0ad1d_0         151 KB  conda-forge
    cffi-1.14.0                |   py36ha419a9e_0         221 KB  conda-forge
    chardet-3.0.4              |py36h9f0ad1d_1006         220 KB  conda-forge
    colorama-0.4.3             |             py_0          17 KB  conda-forge
    cryptography-2.8           |   py36hb32ad35_1         564 KB  conda-forge
    decorator-4.4.2            |             py_0          11 KB  conda-forge
    defusedxml-0.6.0           |             py_0          22 KB  conda-forge
    entrypoints-0.3            |py36h9f0ad1d_1001          12 KB  conda-forge
    idna-2.9                   |             py_1          52 KB  conda-forge
    importlib-metadata-1.6.0   |   py36h9f0ad1d_0          42 KB  conda-forge
    importlib_metadata-1.6.0   |                0           3 KB  conda-forge
    ipykernel-5.2.0            |   py36h5ca1d4c_1         160 KB  conda-forge
    ipython-7.13.0             |   py36h9f0ad1d_2         1.1 MB  conda-forge
    ipython_genutils-0.2.0     |             py_1          21 KB  conda-forge
    jedi-0.16.0                |   py36h9f0ad1d_1         769 KB  conda-forge
    jinja2-2.11.1              |             py_0          94 KB  conda-forge
    json5-0.9.0                |             py_0          24 KB  conda-forge
    jsonschema-3.2.0           |   py36h9f0ad1d_1         107 KB  conda-forge
    jupyter_client-6.1.2       |             py_0          74 KB  conda-forge
    jupyter_core-4.6.3         |   py36h9f0ad1d_1          95 KB  conda-forge
    jupyterlab-2.1.0           |             py_0         5.8 MB  conda-forge
    jupyterlab_server-1.1.0    |             py_0          24 KB  conda-forge
    libsodium-1.0.17           |       h2fa13f4_0         602 KB  conda-forge
    markupsafe-1.1.1           |   py36h68a101e_1          28 KB  conda-forge
    mistune-0.8.4              |py36hfa6e2cd_1000          53 KB  conda-forge
    nbconvert-5.6.1            |           py36_0         506 KB  conda-forge
    nbformat-5.0.4             |             py_0          98 KB  conda-forge
    notebook-4.4.1             |           py36_0         5.7 MB  conda-forge
    openssl-1.1.1f             |       hfa6e2cd_0         4.7 MB  conda-forge
    pandoc-2.9.2               |                0        29.2 MB  conda-forge
    pandocfilters-1.4.2        |             py_1           9 KB  conda-forge
    parso-0.6.2                |             py_0          66 KB  conda-forge
    pickleshare-0.7.5          |py36h9f0ad1d_1001          12 KB  conda-forge
    pip-20.0.2                 |             py_2         1.0 MB  conda-forge
    prompt-toolkit-3.0.5       |             py_0         232 KB  conda-forge
    pycparser-2.20             |             py_0          89 KB  conda-forge
    pygments-2.6.1             |             py_0         683 KB  conda-forge
    pyopenssl-19.1.0           |             py_1          47 KB  conda-forge
    pyrsistent-0.16.0          |   py36h68a101e_0          91 KB  conda-forge
    pysocks-1.7.1              |   py36h9f0ad1d_1          27 KB  conda-forge
    python-3.6.10              |he025d50_1009_cpython        20.7 MB  conda-forge
    python-dateutil-2.8.1      |             py_0         220 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    pywin32-227                |   py36hfa6e2cd_0         6.8 MB  conda-forge
    pyzmq-19.0.0               |   py36ha89082f_1         458 KB  conda-forge
    requests-2.23.0            |     pyh8c360ce_2          47 KB  conda-forge
    setuptools-46.1.3          |   py36h9f0ad1d_0         660 KB  conda-forge
    six-1.14.0                 |             py_1          13 KB  conda-forge
    testpath-0.4.4             |             py_0          85 KB  conda-forge
    tornado-6.0.4              |   py36hfa6e2cd_0         639 KB  conda-forge
    traitlets-4.3.3            |   py36h9f0ad1d_1         133 KB  conda-forge
    urllib3-1.25.7             |   py36h9f0ad1d_1         160 KB  conda-forge
    vc-14.1                    |       h869be7e_1           6 KB  conda-forge
    vs2015_runtime-14.16.27012 |       h30e32a0_1         2.2 MB  conda-forge
    wcwidth-0.1.9              |     pyh9f0ad1d_0          20 KB  conda-forge
    webencodings-0.5.1         |             py_1          12 KB  conda-forge
    wheel-0.34.2               |             py_1          24 KB  conda-forge
    win_inet_pton-1.1.0        |           py36_0           7 KB  conda-forge
    wincertstore-0.2           |        py36_1003          13 KB  conda-forge
    zeromq-4.3.2               |       h6538335_2        10.0 MB  conda-forge
    zipp-3.1.0                 |             py_0          10 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        95.3 MB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bleach             conda-forge/noarch::bleach-3.1.4-pyh9f0ad1d_0
  ca-certificates    conda-forge/win-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/win-64::certifi-2020.4.5.1-py36h9f0ad1d_0
  cffi               conda-forge/win-64::cffi-1.14.0-py36ha419a9e_0
  chardet            conda-forge/win-64::chardet-3.0.4-py36h9f0ad1d_1006
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  cryptography       conda-forge/win-64::cryptography-2.8-py36hb32ad35_1
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  entrypoints        conda-forge/win-64::entrypoints-0.3-py36h9f0ad1d_1001
  idna               conda-forge/noarch::idna-2.9-py_1
  importlib-metadata conda-forge/win-64::importlib-metadata-1.6.0-py36h9f0ad1d_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  ipykernel          conda-forge/win-64::ipykernel-5.2.0-py36h5ca1d4c_1
  ipython            conda-forge/win-64::ipython-7.13.0-py36h9f0ad1d_2
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  jedi               conda-forge/win-64::jedi-0.16.0-py36h9f0ad1d_1
  jinja2             conda-forge/noarch::jinja2-2.11.1-py_0
  json5              conda-forge/noarch::json5-0.9.0-py_0
  jsonschema         conda-forge/win-64::jsonschema-3.2.0-py36h9f0ad1d_1
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.2-py_0
  jupyter_core       conda-forge/win-64::jupyter_core-4.6.3-py36h9f0ad1d_1
  jupyterlab         conda-forge/noarch::jupyterlab-2.1.0-py_0
  jupyterlab_server  conda-forge/noarch::jupyterlab_server-1.1.0-py_0
  libsodium          conda-forge/win-64::libsodium-1.0.17-h2fa13f4_0
  markupsafe         conda-forge/win-64::markupsafe-1.1.1-py36h68a101e_1
  mistune            conda-forge/win-64::mistune-0.8.4-py36hfa6e2cd_1000
  nbconvert          conda-forge/win-64::nbconvert-5.6.1-py36_0
  nbformat           conda-forge/noarch::nbformat-5.0.4-py_0
  notebook           conda-forge/win-64::notebook-4.4.1-py36_0
  openssl            conda-forge/win-64::openssl-1.1.1f-hfa6e2cd_0
  pandoc             conda-forge/win-64::pandoc-2.9.2-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parso              conda-forge/noarch::parso-0.6.2-py_0
  pickleshare        conda-forge/win-64::pickleshare-0.7.5-py36h9f0ad1d_1001
  pip                conda-forge/noarch::pip-20.0.2-py_2
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyrsistent         conda-forge/win-64::pyrsistent-0.16.0-py36h68a101e_0
  pysocks            conda-forge/win-64::pysocks-1.7.1-py36h9f0ad1d_1
  python             conda-forge/win-64::python-3.6.10-he025d50_1009_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/win-64::python_abi-3.6-1_cp36m
  pywin32            conda-forge/win-64::pywin32-227-py36hfa6e2cd_0
  pyzmq              conda-forge/win-64::pyzmq-19.0.0-py36ha89082f_1
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  setuptools         conda-forge/win-64::setuptools-46.1.3-py36h9f0ad1d_0
  six                conda-forge/noarch::six-1.14.0-py_1
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  tornado            conda-forge/win-64::tornado-6.0.4-py36hfa6e2cd_0
  traitlets          conda-forge/win-64::traitlets-4.3.3-py36h9f0ad1d_1
  urllib3            conda-forge/win-64::urllib3-1.25.7-py36h9f0ad1d_1
  vc                 conda-forge/win-64::vc-14.1-h869be7e_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.16.27012-h30e32a0_1
  wcwidth            conda-forge/noarch::wcwidth-0.1.9-pyh9f0ad1d_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py36_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py36_1003
  zeromq             conda-forge/win-64::zeromq-4.3.2-h6538335_2
  zipp               conda-forge/noarch::zipp-3.1.0-py_0

DryRunExit: Dry run. Exiting.

</pre>
</details>

Still digging...

**Comment by jasongrout** [comment]
> jupyterlab -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|3.4.*']

This looks wrong. JLab 2 doesn't support python 2, IIRC. I'm not sure where this constraint is coming from.

**Comment by bollwyvl** [comment]
It did at one point, perhaps... I'll try some more pins...

**Comment by bollwyvl** [comment]
Aha: `notebook` begat `terminado` which begat `winpty` which begat `m2w64-gcc-libs` which demands the [`msys2` channel](https://anaconda.org/msys2). That channel is (unsurprisingly) not set in binder, due to minicondaforge, and my local set up didn't have it either.

Sorry for the noise!

**Comment by bollwyvl** [comment]
For reference:
```
CONDA_SUBDIR=win-64     conda create     --dry-run     --name foo     -c conda-forge     -c msys2     'python>=3.7,<3.9.0a0'     'jupyterlab=2.1' 'nodejs>=10'
```
```
The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bleach             conda-forge/noarch::bleach-3.1.4-pyh9f0ad1d_0
  ca-certificates    conda-forge/win-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/win-64::certifi-2020.4.5.1-py38h32f6830_0
  cffi               conda-forge/win-64::cffi-1.14.0-py38ha419a9e_0
  chardet            conda-forge/win-64::chardet-3.0.4-py38h32f6830_1006
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  cryptography       conda-forge/win-64::cryptography-2.8-py38hb32ad35_1
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  entrypoints        conda-forge/win-64::entrypoints-0.3-py38h32f6830_1001
  idna               conda-forge/noarch::idna-2.9-py_1
  importlib-metadata conda-forge/win-64::importlib-metadata-1.6.0-py38h32f6830_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  ipykernel          conda-forge/win-64::ipykernel-5.2.0-py38h5ca1d4c_1
  ipython            conda-forge/win-64::ipython-7.13.0-py38h32f6830_2
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  jedi               conda-forge/win-64::jedi-0.16.0-py38h32f6830_1
  jinja2             conda-forge/noarch::jinja2-2.11.1-py_0
  json5              conda-forge/noarch::json5-0.9.0-py_0
  jsonschema         conda-forge/win-64::jsonschema-3.2.0-py38h32f6830_1
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.2-py_0
  jupyter_core       conda-forge/win-64::jupyter_core-4.6.3-py38h32f6830_1
  jupyterlab         conda-forge/noarch::jupyterlab-2.1.0-py_0
  jupyterlab_server  conda-forge/noarch::jupyterlab_server-1.1.0-py_1
  libsodium          conda-forge/win-64::libsodium-1.0.17-h2fa13f4_0
  m2w64-gcc-libgfor~ msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         conda-forge/win-64::markupsafe-1.1.1-py38h9de7a3e_1
  mistune            conda-forge/win-64::mistune-0.8.4-py38hfa6e2cd_1000
  msys2-conda-epoch  msys2/win-64::msys2-conda-epoch-20160418-1
  nbconvert          conda-forge/win-64::nbconvert-5.6.1-py38_0
  nbformat           conda-forge/noarch::nbformat-5.0.4-py_0
  nodejs             conda-forge/win-64::nodejs-13.12.0-0
  notebook           conda-forge/win-64::notebook-6.0.3-py38_0
  openssl            conda-forge/win-64::openssl-1.1.1f-hfa6e2cd_0
  pandoc             conda-forge/win-64::pandoc-2.9.2-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parso              conda-forge/noarch::parso-0.6.2-py_0
  pickleshare        conda-forge/win-64::pickleshare-0.7.5-py38h32f6830_1001
  pip                conda-forge/noarch::pip-20.0.2-py_2
  prometheus_client  conda-forge/noarch::prometheus_client-0.7.1-py_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyrsistent         conda-forge/win-64::pyrsistent-0.16.0-py38h9de7a3e_0
  pysocks            conda-forge/win-64::pysocks-1.7.1-py38h32f6830_1
  python             conda-forge/win-64::python-3.8.2-h5fd99cc_5_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/win-64::python_abi-3.8-1_cp38
  pywin32            conda-forge/win-64::pywin32-227-py38hfa6e2cd_0
  pywinpty           conda-forge/win-64::pywinpty-0.5.7-py38_0
  pyzmq              conda-forge/win-64::pyzmq-19.0.0-py38hc5dc6fd_1
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/win-64::setuptools-46.1.3-py38h32f6830_0
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/win-64::sqlite-3.30.1-hfa6e2cd_0
  terminado          conda-forge/win-64::terminado-0.8.3-py38h32f6830_1
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  tornado            conda-forge/win-64::tornado-6.0.4-py38hfa6e2cd_0
  traitlets          conda-forge/win-64::traitlets-4.3.3-py38h32f6830_1
  urllib3            conda-forge/win-64::urllib3-1.25.7-py38h32f6830_1
  vc                 conda-forge/win-64::vc-14.1-h869be7e_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.16.27012-h30e32a0_1
  wcwidth            conda-forge/noarch::wcwidth-0.1.9-pyh9f0ad1d_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py38_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py38_1003
  winpty             conda-forge/win-64::winpty-0.4.3-4
  zeromq             conda-forge/win-64::zeromq-4.3.2-h6538335_2
  zipp               conda-forge/noarch::zipp-3.1.0-py_0



DryRunExit: Dry run. Exiting.
```

**Comment by jasongrout** [comment]
Is this known in conda-forge that a package in conda-forge requires the msys2 channel? It seems a bit sketchy to pull in another gcc package - does it not cause conflicts with other conda-forge packages?

**Comment by bollwyvl** [comment]
The upstream calls out the need for the mingw stack explicitly:
https://github.com/spyder-ide/pywinpty#building-from-source

... and the maintainers/authors certainly aren't amateurs when it comes to this stuff:
https://github.com/conda-forge/pywinpty-feedstock/blob/3b7a173f8c7af6b54b4324ebbe1395bb52902ded/recipe/meta.yaml#L49-L55

I guess it's just One Of Those Things, for now. Thanks again!
