### ISSUE TITLE
Depend upon nodejs so that jupyterlab works out of the box

### ISSUE THREAD

**Issue by westurner** [conda-forge/jupyterlab-feedstock#233]
Issue:

jupyterlab-feedstock should depend upon `-c conda-forge nodejs` so that running `jupyter lab build` with `-c conda-forge jupyterlab` just works ouf of the box.

Is `nodejs` an optional dependency? Sort of.

Should it be possible to just install extensions without having to figure out that you need to also install `nodejs`? Yes.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by westurner** [comment]
See also #159 (I agree that ipywidgets is not a dependency of jupyterlab, but requiring nodejs for jupyterlab should make ipywidgets work, too, right?)

**Comment by jasongrout** [comment]
Thanks. As you point out, this is really an issue/discussion for jlab, not ipywidgets, though it obviously affects using ipywidgets in jlab

(a) For jlab 3, we won't require nodejs for custom packages using the new jlab module system, so fortunately this problem goes away in a few weeks, at least for those that upgrade. we have a new python/conda package for widgets in jlab 3 that installs without needing nodejs.


(b) For the jlab discussion, many people have node installed at the system level, with whatever customizations they have there. While conda does bundle nodejs, there is a question of if we should insist that we use conda's node. But again, that is a discussion for jlab, and will be more of a moot point once jlab 3 comes out in a few weeks.

**Comment by jasongrout** [comment]
Closing since JLab 3.0 is out now, and introduces a new extension distributio method that does not require nodejs to install extensions. See also the discussion at https://github.com/conda-forge/jupyterlab-feedstock/pull/234
