### ISSUE TITLE
This repository doesn't 'just work'

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/jupyterlab-feedstock#274]
A big advantage of conda forge is that packages just work. While the install size might be large, things just install and you can move on with your work.

However, with this package, I always find myself having to go through the steps outlined in https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637

```
mamba install nodejs ipywidgets
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

Is this something we can automate? If not, is there a good reason why we shouldn't do it?

**Comment by bollwyvl** [comment]
The marquee feature of  JupyterLab 3 is basically: the end user of `pip` or `conda` does not need `nodejs` or access to `npmjs.com`, and `jupyter labextension install` is not required for an increasingly large swathe of extensions. Each `pip` package deploys the pre-built files to `$CONDA_PREFIX/share/jupyter/labextensions`. By extension, `conda-build` should not even need to invoke `nodejs`, or contact `npmjs.com` during the build. 

For `ipywidgets`, in specific, the jupyterlab 3 assets are delivered by its dependency `jupyterlab_widgets`. I personally prefer this pattern, but the pattern of distributing client assets (to be used by the server) along with kernel assets (e.g. the python widget classes) is probably here to stay unless we can figure out a clever pattern.

https://github.com/conda-forge/conda-forge.github.io/issues/1421#issuecomment-828838627

**Comment by jasongrout** [comment]
In short, with jlab 3, you just mamba install ipywidgets and jupyterlab and you are done. No need to install nodejs or your last two lines above. Just

mamba install ipywidgets jupyterlab

**Comment by hmaarrfk** [comment]
Let me try

**Comment by hmaarrfk** [comment]
Wow, thank you so much.

Sorry old memory betrayed me.

```
mamba install jupyterlab ipywidgets tqdm
```
yileded


![image](https://user-images.githubusercontent.com/90008/118204643-b4370f00-b42c-11eb-95ae-7495dac713fa.png)
