### ISSUE TITLE
Question about `nodejs` testing requirement

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/jupyterlab-feedstock#337]
### Comment:

In the test requirements there's the following constraint on `nodejs`. Am curious what the origin of this constraint is and what issues it is working around

https://github.com/conda-forge/jupyterlab-feedstock/blob/5992f06618c47a7296fc1be032f1d134335e99bd/recipe/meta.yaml#L39-L41

**Comment by bollwyvl** [comment]
Trying to keep LTS:
https://github.com/conda-forge/nodejs-feedstock/issues/223

Got no time for randomly-broken bleeding-edge (or discarded) stuff.

**Comment by fcollonval** [comment]
Closing as answered
