### ISSUE TITLE
Wrong jupyterlab-server dependency

### ISSUE THREAD

**Issue by krassowski** [conda-forge/jupyterlab-feedstock#433]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Upstream defined `jupyterlab_server>=2.27.1,<3"`, recipe defines:

https://github.com/conda-forge/jupyterlab-feedstock/blob/d79f7828f6e95b07e4f3add5c3e10e07ee38a67d/recipe/meta.yaml#L38

See https://github.com/jupyterlab/jupyterlab/issues/16317

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by bollwyvl** [comment]
This has now been patched, and is as fixed as it's going to get, i suppose.
